### ISSUE TITLE
ValueError: The element '<xpath expr="//nav[@id='oe_main_menu_navbar']">'

### ISSUE THREAD

**Issue by percevaq** [Openworx/backend_theme#29]
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/werkzeug/serving.py", line 180, in run_wsgi
    execute(self.server.app)
  File "/usr/lib/python2.7/dist-packages/werkzeug/serving.py", line 168, in execute
    application_iter = app(environ, start_response)
  File "/opt/odoo/server/odoo/service/server.py", line 249, in app
    return self.app(e, s)
  File "/opt/odoo/server/odoo/service/wsgi_server.py", line 184, in application
    return werkzeug.contrib.fixers.ProxyFix(application_unproxied)(environ, start_response)
  File "/usr/lib/python2.7/dist-packages/werkzeug/contrib/fixers.py", line 148, in __call__
    return self.app(environ, start_response)
  File "/opt/odoo/server/odoo/service/wsgi_server.py", line 172, in application_unproxied
    result = handler(environ, start_response)
  File "/opt/odoo/server/odoo/http.py", line 1308, in __call__
    return self.dispatch(environ, start_response)
  File "/opt/odoo/server/odoo/http.py", line 1282, in __call__
    return self.app(environ, start_wrapped)
  File "/usr/lib/python2.7/dist-packages/werkzeug/wsgi.py", line 591, in __call__
    return self.app(environ, start_response)
  File "/opt/odoo/server/odoo/http.py", line 1481, in dispatch
    result = ir_http._dispatch()
  File "/opt/odoo/server/addons/website_sale/models/ir_http.py", line 15, in _dispatch
    return super(IrHttp, cls)._dispatch()
  File "/opt/odoo/server/addons/website/models/ir_http.py", line 218, in _dispatch
    resp = super(Http, cls)._dispatch()
  File "/opt/odoo/server/addons/web_editor/models/ir_http.py", line 21, in _dispatch
    return super(IrHttp, cls)._dispatch()
  File "/opt/odoo/server/addons/utm/models/ir_http.py", line 20, in _dispatch
    response = super(IrHttp, cls)._dispatch()
  File "/opt/odoo/server/odoo/addons/base/ir/ir_http.py", line 199, in _dispatch
    return cls._handle_exception(e)
  File "/opt/odoo/server/addons/website/models/ir_http.py", line 270, in _handle_exception
    return super(Http, cls)._handle_exception(exception)
  File "/opt/odoo/server/odoo/addons/base/ir/ir_http.py", line 169, in _handle_exception
    return request._handle_exception(exception)
  File "/opt/odoo/server/odoo/http.py", line 768, in _handle_exception
    return super(HttpRequest, self)._handle_exception(exception)
  File "/opt/odoo/server/odoo/addons/base/ir/ir_http.py", line 195, in _dispatch
    result = request.dispatch()
  File "/opt/odoo/server/odoo/http.py", line 827, in dispatch
    r = self._call_function(**self.params)
  File "/opt/odoo/server/odoo/http.py", line 333, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/server/odoo/service/model.py", line 101, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/server/odoo/http.py", line 329, in checked_call
    result.flatten()
  File "/opt/odoo/server/odoo/http.py", line 1259, in flatten
    self.response.append(self.render())
  File "/opt/odoo/server/odoo/http.py", line 1252, in render
    return env["ir.ui.view"].render_template(self.template, self.qcontext)
  File "/opt/odoo/server/odoo/addons/base/ir/ir_ui_view.py", line 1043, in render_template
    return self.browse(self.get_view_id(template)).render(values, engine)
  File "/opt/odoo/server/addons/website/models/ir_ui_view.py", line 115, in render
    return super(View, self).render(values, engine=engine)
  File "/opt/odoo/server/addons/web_editor/models/ir_ui_view.py", line 26, in render
    return super(IrUiView, self).render(values=values, engine=engine)
  File "/opt/odoo/server/odoo/addons/base/ir/ir_ui_view.py", line 1063, in render
    return self.env[engine].render(self.id, qcontext)
  File "/opt/odoo/server/odoo/addons/base/ir/ir_qweb/ir_qweb.py", line 53, in render
    return super(IrQWeb, self).render(id_or_xml_id, values=values, **context)
  File "/opt/odoo/server/odoo/addons/base/ir/ir_qweb/qweb.py", line 248, in render
    self.compile(template, options)(self, body.append, values or {})
  File "<decorator-gen-19>", line 2, in compile
    
  File "/opt/odoo/server/odoo/tools/cache.py", line 87, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/opt/odoo/server/odoo/addons/base/ir/ir_qweb/ir_qweb.py", line 73, in compile
    return super(IrQWeb, self).compile(id_or_xml_id, options=options)
  File "/opt/odoo/server/odoo/addons/base/ir/ir_qweb/qweb.py", line 265, in compile
    element, document = self.get_template(template, options)
  File "/opt/odoo/server/odoo/addons/base/ir/ir_qweb/qweb.py", line 345, in get_template
    raise QWebException("load could not load template", name=template)
QWebException: None
Traceback (most recent call last):
  File "/opt/odoo/server/odoo/addons/base/ir/ir_qweb/qweb.py", line 341, in get_template
    document = options.get('load', self.load)(template, options)
  File "/opt/odoo/server/odoo/addons/base/ir/ir_qweb/ir_qweb.py", line 81, in load
    template = env['ir.ui.view'].read_template(name)
  File "/opt/odoo/server/odoo/addons/base/ir/ir_ui_view.py", line 938, in read_template
    return self._read_template(self.get_view_id(xml_id))
  File "<decorator-gen-9>", line 2, in _read_template
  File "/opt/odoo/server/odoo/tools/cache.py", line 87, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/opt/odoo/server/odoo/addons/base/ir/ir_ui_view.py", line 929, in _read_template
    arch = self.browse(view_id).read_combined(['arch'])['arch']
  File "/opt/odoo/server/odoo/addons/base/ir/ir_ui_view.py", line 668, in read_combined
    arch = self.apply_view_inheritance(arch_tree, root.id, self.model)
  File "/opt/odoo/server/odoo/addons/base/ir/ir_ui_view.py", line 617, in apply_view_inheritance
    source = self.apply_inheritance_specs(source, specs_tree, view_id)
  File "/opt/odoo/server/odoo/addons/base/ir/ir_ui_view.py", line 595, in apply_inheritance_specs
    self.raise_view_error(_("Element '%s' cannot be located in parent view") % tag, inherit_id)
  File "/opt/odoo/server/odoo/addons/base/ir/ir_ui_view.py", line 468, in raise_view_error
    raise ValueError(message)
ValueError: El elemento '<xpath expr="//nav[@id='oe_main_menu_navbar']">' no puede ser localizado en la vista padre

Error de contexto:
Vista `App Drawer - Web Client`
[view_id: 1303, xml_id: web_responsive.webclient_bootstrap, model: n/a, parent_id: 173]

load could not load template
Template: 173

**Comment by mgielissen** [comment]
Use web_responsive from v10.0 for the time being (works also in v11). It is possible that web_responsive v11 is not yet 100% ready.

**Comment by percevaq** [comment]
Thank for yout quick reponse.

Im use web_responsive 10.0 last update Commits on Oct 16, 2017 and las update backend_them Tue Oct 17 11:14:58 2017.

**Comment by percevaq** [comment]
Ops... sorry... update odoo server to Wed Oct 18 12:16:27 2017 +0200 ,restart update_all and 
already working properly.
Thank
